### PR TITLE
Add vector icons matching IntelliJ 2018.2 theme

### PR DESCRIPTION
**Pull request by tan9**
Matching the new icon style introduced in [IntelliJ 2018.2](https://blog.jetbrains.com/blog/2018/06/26/new-icons-in-intellij-platform-2018-2/).

Now looks like:
Screenshot from 2019-06-14 17-49-34

### CODE REVIEW

**Comment by tan9** [comment]
@krasa is the icons in this PR meet the quality requirements of this plugin?

**Comment by krasa** [comment]
It's beautiful ❤️

**Comment by krasa** [comment]
Only, is there any particular reason why the color is more yellow, than the logo?
image
image

**Comment by tan9** [comment]
Hi @krasa, I just picked the color from [Color of Action Icons](https://jetbrains.github.io/ui/principles/icons/#action-icons) listed in the [IntelliJ Platform UI Guidelines](https://jetbrains.github.io/ui/).

Although there exists wider palette for [Noun Icons](https://jetbrains.github.io/ui/principles/icons/#noun-icons)  in the same guideline for tree views. But since our icon is located in the toolbar. It should be a good idea not to try to clutter it up :)

**Comment by tan9** [comment]
In #28, I changed the console16.svg and its dark variant to grey color according to the [guideline](https://jetbrains.github.io/ui/principles/icons/#25).

**Comment by krasa** [comment]
Well, I think the whole gray style of icons is a collosal mistake. That's why I have https://github.com/krasa/IdeaIconPack

More so after they've made a theme contest which goes against everythig they've done https://plugins.jetbrains.com/contest/intellij-themes/2019

Orange is an established color of VisualVM's logo, so it should be that. It will look good everywhere, but gray one would look disabled for people that have colorful themes.

**Pull request merged**
